/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.AmigoDAO;
import dao.EmprestimoDAO;
import dao.FerramentaDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Emprestimo;
import modelo.Ferramenta;

/**
 *
 * @author leand
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        renderEmprestimosTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTEmprestimos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JBEmprestarFerramenta = new javax.swing.JButton();
        JBEstornar = new javax.swing.JButton();
        JBRelatorios = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMAmigos = new javax.swing.JMenu();
        JMFerramentas = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(0, 71, 119));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 550));

        jScrollPane1.setBackground(new java.awt.Color(72, 169, 166));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 252));

        JTEmprestimos.setBackground(new java.awt.Color(204, 204, 204));
        JTEmprestimos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        JTEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amigo", "Ferramenta", "Quantidade", "Desde:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTEmprestimos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JTEmprestimos.setGridColor(new java.awt.Color(51, 51, 51));
        JTEmprestimos.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        JTEmprestimos.setShowGrid(false);
        jScrollPane1.setViewportView(JTEmprestimos);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Empréstimos pendentes:");

        JBEmprestarFerramenta.setBackground(new java.awt.Color(73, 159, 104));
        JBEmprestarFerramenta.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        JBEmprestarFerramenta.setForeground(new java.awt.Color(255, 255, 255));
        JBEmprestarFerramenta.setText("Emprestar ferramenta");
        JBEmprestarFerramenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBEmprestarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEmprestarFerramentaActionPerformed(evt);
            }
        });

        JBEstornar.setBackground(new java.awt.Color(186, 63, 29));
        JBEstornar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        JBEstornar.setForeground(new java.awt.Color(255, 255, 255));
        JBEstornar.setText("Estornar");
        JBEstornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBEstornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEstornarActionPerformed(evt);
            }
        });

        JBRelatorios.setBackground(new java.awt.Color(73, 159, 104));
        JBRelatorios.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        JBRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        JBRelatorios.setText("Relatórios");
        JBRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JBRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBEstornar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBEmprestarFerramenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBEmprestarFerramenta)
                    .addComponent(JBRelatorios))
                .addGap(27, 27, 27)
                .addComponent(JBEstornar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 71, 119));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 252));

        JMAmigos.setBackground(new java.awt.Color(255, 255, 252));
        JMAmigos.setForeground(new java.awt.Color(255, 255, 252));
        JMAmigos.setText("Amigos");
        JMAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMAmigosMouseClicked(evt);
            }
        });
        JMAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMAmigosActionPerformed(evt);
            }
        });
        jMenuBar1.add(JMAmigos);

        JMFerramentas.setForeground(new java.awt.Color(255, 255, 252));
        JMFerramentas.setText("Ferramentas");
        JMFerramentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMFerramentasMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMFerramentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void renderEmprestimosTable() {
        FerramentaDAO daoF = new FerramentaDAO();
        AmigoDAO daoA = new AmigoDAO(); 
        EmprestimoDAO dao = new EmprestimoDAO();
        ArrayList<Emprestimo> ferramentas = dao.getMinhaLista();
        DefaultTableModel model = (DefaultTableModel) JTEmprestimos.getModel();

        for (Emprestimo emp : ferramentas) {
            if (emp.getQuantidade() != 0) {
                String nomeAmigo = daoA.carregaAmigo(emp.getAmigo()).getNome();
                String nomeFerramenta = daoF.carregaFerramenta(emp.getFerramenta()).getNome();
                model.addRow(new Object[]{
                    nomeAmigo, 
                    nomeFerramenta, 
                    emp.getQuantidade(), 
                    emp.getDataEmprestimo(), 
                });
            }
        }
    }

    private void JBEmprestarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEmprestarFerramentaActionPerformed
        JFCriarAluguel objeto = new JFCriarAluguel();
        objeto.setLocationRelativeTo(null);
        objeto.setVisible(true);
    }//GEN-LAST:event_JBEmprestarFerramentaActionPerformed

    private void JBEstornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEstornarActionPerformed
        JFDevolverFerramenta objeto = new JFDevolverFerramenta();
        objeto.setLocationRelativeTo(null);
        objeto.setVisible(true);
    }//GEN-LAST:event_JBEstornarActionPerformed

    private void JMAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMAmigosActionPerformed

    }//GEN-LAST:event_JMAmigosActionPerformed

    private void JBRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRelatoriosActionPerformed
        // TODO add your handling code here:
        JFRelatorios objeto = new JFRelatorios();
        objeto.setLocationRelativeTo(null);
        objeto.setVisible(true);
    }//GEN-LAST:event_JBRelatoriosActionPerformed

    private void JMFerramentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMFerramentasMouseClicked
        // TODO add your handling code here:
        JFGerenciarFerramentas objeto = new JFGerenciarFerramentas();
        objeto.setLocationRelativeTo(null);
        objeto.setVisible(true);
    }//GEN-LAST:event_JMFerramentasMouseClicked

    private void JMAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMAmigosMouseClicked
        // TODO add your handling code here:
        JFGerenciarAmigos objeto = new JFGerenciarAmigos();
        objeto.setLocationRelativeTo(null);
        objeto.setVisible(true);
    }//GEN-LAST:event_JMAmigosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEmprestarFerramenta;
    private javax.swing.JButton JBEstornar;
    private javax.swing.JButton JBRelatorios;
    private javax.swing.JMenu JMAmigos;
    private javax.swing.JMenu JMFerramentas;
    private javax.swing.JTable JTEmprestimos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
